########################################################
# API Gateway HTTP Client (vscode extension installed) #
########################################################

# @name authRequest@
POST http://keykloak.empresa.com.br/auth/realms/meu-realm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id=meu-client
&client_secret=lklUeZGplGltFiVBvm2KvXgDz1nmWpRr

###########################################
GET http://localhost:8080/actuator/gateway/routes
Content-Type: application/json
Authorization: Bearer {{authRequest.response.body.access_token}}
