spring:
  cloud:
    gateway:
      httpclient: #Resiliencia e Desempenho
        connect-timeout: 5000
        response-timeout: 10s
    loadbalancer:
      cache:
        caffeine:
          spec: maximumSize=500,expireAfterAccess=600s