server:
  forward-headers-strategy: FRAMEWORK

spring:
  application:
    name: api-gateway
  # webflux:
  #   base-path: /gwt
  profiles:
    active:
      - dev
  cloud:
    gateway:
      x-forwarded:
        enabled: true
        host-enabled: true
        port-enabled: true
        for-enabled: true
        proto-enabled: true
        prefix-enabled: true
      httpclient:
        ssl:
          use-insecure-trust-manager: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - TokenRelay=
        - SaveSession

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
  security:
    oauth2:
       resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URI_SERVER}
       client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_API_GATEWAY_CLIENT_ID}
            client-secret: ${KEYCLOAK_API_GATEWAY_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_URI_SERVER}
            user-name-attribute: preferred_username

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${SPRING_CLOUD_EUREKA_HOST}:${SPRING_CLOUD_EUREKA_PORT}${SPRING_CLOUD_EUREKA_PATH}

management:
  server:
    base-path: /gwt
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: api-gateway