server:
  port: 8080
  forward-headers-strategy: native

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: httpbin-route
              uri: https://httpbin.org
              predicates:
                - Path=/get
              filters:
                - AddRequestHeader=X-Test, SpringCloudGateway

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/