spring:
  cloud:
    gateway:
      httpclient: #Resiliencia e Desempenho
        connect-timeout: 5000
        response-timeout: 10s
    loadbalancer:
      cache:
        caffeine:
          spec: maximumSize=500,expireAfterAccess=600s

# logging:
#   level:
#     root: WARN
#     '[org.springframework.cloud.gateway]': WARN
#     '[org.springframework.http.server.reactive]': ERROR
#     '[org.springframework.web.reactive]': ERROR
#     '[org.springframework.boot.autoconfigure.web]': ERROR
#     '[org.springframework.boot.context.logging]': WARN
#     '[redisratelimiter]': ERROR
#     '[reactor.ipc.netty]': WARN
#     '[reactor.netty]': WARN
#     '[reactor.netty.http.client]': WARN
#     '[org.springframework.security]': WARN
#     '[org.springframework.security.oauth2]': ERROR
#     '[org.springframework.web.reactive.function.client]': ERROR
#     '[org.springframework.jdbc.core.JdbcTemplate]': ERROR